# Generated by Django 5.0.1 on 2024-02-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigocurso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideosCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocurso', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
