# Generated by Django 5.0.1 on 2024-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinalsArchives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.IntegerField()),
                ('linkvideo', models.CharField(max_length=1000)),
                ('descricaoptbr', models.CharField(max_length=2000)),
                ('descricaolibras', models.CharField(max_length=1000)),
            ],
        ),
    ]
