# Generated by Django 5.0.1 on 2024-02-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicursos', '0003_sinalsarchives_codigocurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomemateria', models.CharField()),
                ('codigomateria', models.IntegerField()),
                ('codigocurso', models.IntegerField()),
            ],
        ),
    ]
