# Generated by Django 5.0.1 on 2024-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicursos', '0004_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinalsarchives',
            name='codigodamateria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nomemateria',
            field=models.CharField(max_length=1000),
        ),
    ]
