# Generated by Django 5.0.1 on 2024-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicursos', '0005_sinalsarchives_codigodamateria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinalsarchives',
            name='linkqrcode',
            field=models.TextField(default='lll'),
        ),
    ]
